### ISSUE TITLE
Benchmark Proposal: many small arrays VS few large spen-ed arrays

### ISSUE THREAD

**Issue by ZacharyPatten** [dotneters/dotnet-benchmarks#13]
I topic that I have seen asked regarding C# is whether it is better to perform large allocations and segment them or just do lots of smaller allocations.

Might make a useful benchmark.

**Comment by ZacharyPatten** [comment]
I had an idea for this but I honestly can't remember now... I'm just gonna close this...

**Comment by WhiteBlackGoose** [comment]
Btw fwiw it's definitely better to perform a large allocation if it's a long-term one
